:smtp_options:
  :address: 'smtp.gmail.com'
  :port: '587'
  :enable_starttls_auto: true
  :user_name: 'login'
  :password: 'password'
  :authentication: :plain # :plain, :login, :cram_md5, no auth by default